const matches = [
  {
    _id: "977cd349-b90f-47b3-9985-92a28fa206da",
    league: { _id: "5b21ca3eeb7f6fbccd471820", name: "PRD" },
    date: "1/22/2022",
    time: "9:56 PM",
    vs: "United Kingdom vs Czech Republic",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "6902a534-7a97-4b15-859c-9968e272c229",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "CLF" },
    date: "9/22/2021",
    time: "9:31 AM",
    vs: "Indonesia vs Australia",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "5606a8ca-3b88-43c8-9657-5829e313f333",
    league: { _id: "5b21ca3eeb7f6fbccd471820", name: "PRD" },
    date: "4/10/2022",
    time: "8:09 AM",
    vs: "Czech Republic vs Indonesia",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "fb729124-ea36-46d0-9bf1-0c567ef97687",
    league: { _id: "5b21ca3eeb7f6fbccd471814", name: "UCL" },
    date: "10/27/2021",
    time: "2:37 PM",
    vs: "Canada vs Ireland",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "d26e8ffb-d64c-4b96-953d-30d0ba27ce4e",
    league: { _id: "5b21ca3eeb7f6fbccd471820", name: "PRD" },
    date: "10/10/2021",
    time: "6:28 AM",
    vs: "Philippines vs Portagal",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "4579d515-22b1-45d5-ba8a-e674755fde51",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "CLF" },
    date: "2/11/2022",
    time: "5:29 AM",
    vs: "China vs India",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "137f7a2c-c896-4001-85c5-dfa569289487",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "CLF" },
    date: "11/8/2021",
    time: "12:18 PM",
    vs: "China vs Pakistan",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "31568a93-2077-44da-b1fa-2c8ed41a9569",
    league: { _id: "5b21ca3eeb7f6fbccd471820", name: "PRD" },
    date: "11/13/2021",
    time: "9:42 AM",
    vs: "Poland vs Iran",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "2152f4f4-359f-45e8-956f-c03fff452d07",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "CLF" },
    date: "12/19/2021",
    time: "1:30 PM",
    vs: "Russia vs America",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "448bebc6-dffe-465a-83f1-3ffabf0f445d",
    league: { _id: "5b21ca3eeb7f6fbccd471814", name: "UCL" },
    date: "4/17/2022",
    time: "12:30 AM",
    vs: "China vs America",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "0843b532-b940-4a54-a2d6-c665bd05b614",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "CLF" },
    date: "1/12/2022",
    time: "2:56 AM",
    vs: "Russia vs China",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "a51e7610-20f2-44e4-8245-5c2455269279",
    league: { _id: "5b21ca3eeb7f6fbccd471820", name: "PRD" },
    date: "3/9/2022",
    time: "1:37 PM",
    vs: "Colombia vs Singapore",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "e4e56652-cb60-43aa-9c60-109ff291b864",
    league: { _id: "5b21ca3eeb7f6fbccd471814", name: "UCL" },
    date: "2/5/2022",
    time: "9:40 AM",
    vs: "Sweden vs Turkey",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "2f2027a6-2134-452e-a35b-acf8366e94c4",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "CLF" },
    date: "6/19/2022",
    time: "11:35 AM",
    vs: "China vs Russia",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "f6e97470-edec-4d2f-bb72-926cec9b197b",
    league: { _id: "5b21ca3eeb7f6fbccd471820", name: "PRD" },
    date: "6/23/2021",
    time: "10:37 AM",
    vs: "Yemen vs Arab",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "c19e5421-18a8-4faf-9d66-1e22b8fa119f",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "CLF" },
    date: "7/15/2021",
    time: "7:32 AM",
    vs: "Morocco vs England",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "116b1998-92ec-49c9-9010-c242d764c032",
    league: { _id: "5b21ca3eeb7f6fbccd471814", name: "UCL" },
    date: "5/11/2022",
    time: "4:07 PM",
    vs: "Brazil vs Portagal",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "79c7e0fb-9ca3-4bf6-8d56-323261804ce8",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "CLF" },
    date: "5/31/2022",
    time: "9:36 AM",
    vs: "Jamaica vs Brazil",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
  {
    _id: "23200b19-86b5-4a40-9d2f-4ce81f6f2d9a",
    league: { _id: "5b21ca3eeb7f6fbccd471814", name: "UCL" },
    date: "11/30/2021",
    time: "11:16 AM",
    vs: "Philippines vs Russia",
    channels: [
      { ch_name: "SONY LIVE" },
      { ch_name: "ESPN" },
      { ch_name: "Grimmiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Verbenaceae" },
      { ch_name: "Polygalaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Ten Sports" },
      { ch_name: "Asteraceae" },
    ],
  },
  {
    _id: "1c17b2df-ace9-448a-afbb-daa703ae426b",
    league: { _id: "5b21ca3eeb7f6fbccd471820", name: "PRD" },
    date: "5/23/2022",
    time: "9:04 AM",
    vs: "Japan vs China",
    channels: [
      { ch_name: "Ten Sports" },
      { ch_name: "Cactaceae" },
      { ch_name: "Fagaceae" },
      { ch_name: "Rosaceae" },
      { ch_name: "Cyperaceae" },
      { ch_name: "Arthoniaceae" },
      { ch_name: "Agavaceae" },
      { ch_name: "PTV Sports" },
      { ch_name: "Helodiaceae" },
      { ch_name: "SKY Sports" },
      { ch_name: "Apiaceae" },
    ],
  },
];

export function getMatches() {
  return matches;
}

export function getMatch(id) {
  return matches.find((m) => m._id === id);
}

export function deleteMatches(id) {
  let matchInDb = matches.find((m) => m._id === id);
  matches.splice(matches.indexOf(matchInDb), 1);
  return matchInDb;
}
