export const teams = [
  {
    _id: "5b21ca3eeb7f6fbccd471818",
    name: "ENERGETIK-BGU",
    league: { _id: "5b21ca3eeb7f6fbccd471820", name: "English Premier League" },
    standings: 12,
    players: [
      { player_name: "SONY LIVE" },
      { player_name: "ESPN" },
      { player_name: "Grimmiaceae" },
      { player_name: "SKY Sports" },
      { player_name: "Verbenaceae" },
      { player_name: "Polygalaceae" },
      { player_name: "SKY Sports" },
      { player_name: "Ten Sports" },
      { player_name: "Asteraceae" },
    ],
  },
  {
    _id: "5b21ca3eeb7f6fbccd471814",
    name: "FC MINSK",
    league: { _id: "5b21ca3eeb7f6fbccd471818", name: "Balarus" },
    standings: 11,
    players: [
      { player_name: "SONY LIVE" },
      { player_name: "ESPN" },
      { player_name: "Grimmiaceae" },
      { player_name: "SKY Sports" },
      { player_name: "Verbenaceae" },
      { player_name: "Polygalaceae" },
      { player_name: "SKY Sports" },
      { player_name: "Ten Sports" },
      { player_name: "Asteraceae" },
    ],
  },
  {
    _id: "5b21ca3eeb7f6fbccd471820",
    name: "NAFTAN",
    league: { _id: "5b21ca3eeb7f6fbccd471814", name: "Laliga" },
    standings: 18,
    players: [
      { player_name: "SONY LIVE" },
      { player_name: "ESPN" },
      { player_name: "Grimmiaceae" },
      { player_name: "SKY Sports" },
      { player_name: "Verbenaceae" },
      { player_name: "Polygalaceae" },
      { player_name: "SKY Sports" },
      { player_name: "Ten Sports" },
      { player_name: "Asteraceae" },
    ],
  },
];
